import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import type { CandidateRule,Evidence } from '../candidate.ts';
import type { ParsedBlock,ParsedDocument,SourceLocator } from '../parsedDocument.ts';
import type { SemanticBinding } from '../v3/contract.ts';
import { extractFacts,type ExtractedFact } from '../v3/facts.ts';
import { buildTaskInput,V3_TASKS,type SemanticTask } from '../v3/tasks.ts';
import { buildFrozenBenchmarkPack,createStructuredBenchmarkProvider,runFrozenBenchmark,SMALL_PROFILE,verifyFrozenBenchmarkPack } from './benchmarkPack.ts';
import { compareModelResult,notMeasuredMetric,type AuditMetric } from './comparison.ts';
import { classifyPreferredEvidence } from './evidence.ts';
import { validateExceptionRelations } from './exceptionRelations.ts';
import { replayV41 } from './replay.ts';
import { validateSemanticBindingV41 } from './semanticSafety.ts';

const locator=(paragraphIndex:number):SourceLocator=>({kind:'HWP_RECORD',pageNumber:null,stream:'BodyText/Section0',recordOffset:paragraphIndex*10,recordLevel:0,paragraphIndex});
function documentOf(texts:string[]):ParsedDocument{const blocks:ParsedBlock[]=texts.map((text,index)=>({id:`b${String(index).padStart(6,'0')}`,type:'paragraph',text,sectionPath:[],sourceLocator:locator(index)})),text=blocks.map(block=>block.text).join('\n');return {schemaVersion:1,documentId:`sha256:${'d'.repeat(64)}`,sha256:'d'.repeat(64),mimeType:'application/x-hwp',parserVersion:'document-parser-v1',status:'PARSED',pages:null,blocks,tables:[],metadata:{},quality:{textBlockCount:blocks.length,tableCount:0,characterCount:[...text].length,emptyBlockRatio:0,replacementCharacterCount:0,suspiciousEncoding:false,parserWarnings:[],extractionAllowed:true}};}
const task=(name:string)=>V3_TASKS.find(item=>item.name===name)!;
const bind=(role:string,facts:ExtractedFact[]):SemanticBinding=>({bindingId:'binding',semanticRole:role,factIds:facts.map(f=>f.factId),sourceIds:[...new Set(facts.map(f=>f.sourceId))],qualifierSourceIds:[]});
const fact=(facts:ExtractedFact[],value:number,unit?:string)=>facts.find(item=>item.normalizedValue===value&&(!unit||item.unit===unit))!;

test('income guard rejects cross-bound band and childbirth contexts',()=>{const document=documentOf(['청년 특별공급 신청자 본인 월평균소득 70% 이하','청년 출산가구 소득기준 완화 140% 이하']),facts=extractFacts(document);for(const selected of [fact(facts,70),fact(facts,140)]){const result=validateSemanticBindingV41(document,task('youth.income'),bind('YOUTH.INCOME_LIMIT',[selected]),facts,facts);assert.equal(result.status,'REJECTED');}});
test('asset guard separates total assets from subscription savings',()=>{const document=documentOf(['생애최초 특별공급 세대 총자산 362백만원 이하','생애최초 특별공급 청약저축 선납금 포함 600만원 이상']),facts=extractFacts(document),selected=fact(facts,6_000_000);const result=validateSemanticBindingV41(document,task('firstTime.financial'),bind('FIRST_TIME.ASSET_LIMIT',[selected]),facts,facts);assert.equal(result.status,'REJECTED');assert.ok(result.issues.some(item=>item.code.includes('ASSET')));});
test('parent asset scope is not interchangeable with applicant assets',()=>{const document=documentOf(['청년 특별공급 신청자 본인 자산 276백만원 이하, 부모 자산 1,034백만원 이하']),facts=extractFacts(document),selected=fact(facts,276_000_000);const result=validateSemanticBindingV41(document,task('youth.assets'),bind('YOUTH.PARENT_ASSET_LIMIT',[selected]),facts,facts);assert.equal(result.status,'REJECTED');assert.ok(result.issues.some(item=>item.category==='WRONG_SCOPE'||item.category==='WRONG_SEMANTIC_ROLE'));});
test('score guard accepts score facts only and forbids first-time score',()=>{const document=documentOf(['청년 특별공급 가점 해당 구간 3점, 최대 9점']),facts=extractFacts(document),scores=facts.filter(item=>item.type==='SCORE');const youth=validateSemanticBindingV41(document,task('youth.score'),bind('YOUTH.SCORE.TOTAL',scores),facts,facts);assert.ok(!youth.issues.some(item=>item.code==='SCORE_FACT_TYPE_REQUIRED'));const synthetic:SemanticTask={name:'firstTime.score',scope:'FIRST_TIME',stage:'COMMON',keywords:['점'],allowedRoles:['FIRST_TIME.SCORE.TOTAL'],expectedBindings:{min:1,max:2}};const first=validateSemanticBindingV41(document,synthetic,bind('FIRST_TIME.SCORE.TOTAL',scores),facts,facts);assert.equal(first.status,'REJECTED');assert.ok(first.issues.some(item=>item.code==='CRITICAL_SCORE_VIOLATION'));});
test('range guard rejects a single boundary taken from a range',()=>{const document=documentOf(['청년 특별공급 가점 월평균소득 70% 초과 100% 이하']),facts=extractFacts(document),selected=fact(facts,70);const result=validateSemanticBindingV41(document,task('youth.income'),bind('YOUTH.INCOME_LIMIT',[selected]),facts,facts);assert.ok(result.issues.some(item=>item.code.startsWith('PARTIAL_RANGE_BINDING')));});
test('scope guard catches wrong parent scope',()=>{const document=documentOf(['청년 특별공급 신청자 본인 자산 1,034백만원 이하']),facts=extractFacts(document),selected=fact(facts,1_034_000_000);const result=validateSemanticBindingV41(document,task('youth.assets'),bind('YOUTH.PARENT_ASSET_LIMIT',[selected]),facts,facts);assert.ok(result.issues.some(item=>item.category==='WRONG_SCOPE'));});
test('exception relations distinguish linked, orphan, missing and wrong relations',()=>{const rows=validateExceptionRelations(['base.region'],['exception.overseas','exception.spouse'],[{baseRuleKey:'base.region',exceptionRuleKey:'exception.overseas',type:'LIMITED_BY'},{baseRuleKey:'missing',exceptionRuleKey:'exception.spouse',type:'APPLIES_ONLY_IF'}],['exception.overseas','exception.childbirth']);assert.ok(rows.some(row=>row.status==='LINKED'));assert.ok(rows.some(row=>row.status==='MISSING_EXCEPTION'));assert.ok(rows.some(row=>row.status==='WRONG_RELATION'));});
test('preferred evidence distinguishes exact, equivalent, valid alternative and mismatch',()=>{const a={documentId:'d',blockId:null,tableId:'t',row:1,column:1,snippet:'a',locator:locator(1)} as Evidence,b={...a,row:2,column:2,locator:locator(2)},c={...a,tableId:'u',locator:locator(3)};assert.equal(classifyPreferredEvidence([a],[a],true),'EXACT_LOCATOR_MATCH');assert.equal(classifyPreferredEvidence([a],[b],true),'EQUIVALENT_SOURCE_SUPPORT');assert.equal(classifyPreferredEvidence([a],[c],true),'DIFFERENT_BUT_VALID');assert.equal(classifyPreferredEvidence([a],[a],false),'SEMANTIC_MISMATCH');});

test('frozen pack is hash-verified and providers receive the same immutable tasks',async()=>{const document=documentOf(['청년 특별공급 신청자 본인 월평균소득 140% 이하','청년 특별공급 신청자 본인 자산 276백만원 이하 부모 자산 1,034백만원 이하','신혼부부 특별공급 세대 총자산 362백만원 이하','생애최초 특별공급 청약저축 선납금 포함 600만원 이상 세대 총자산 362백만원 이하']);const facts=extractFacts(document),pack=buildFrozenBenchmarkPack(document,facts),again=buildFrozenBenchmarkPack(document,facts);assert.ok(verifyFrozenBenchmarkPack(pack));assert.equal(pack.hash,again.hash);assert.equal(pack.profiles.SMALL.length,SMALL_PROFILE.length);const seen:string[]=[];const provider={id:'mock',model:'offline',async bind(input:any){seen.push(JSON.stringify(input));return {bindings:[],unresolved:[]};}};const run=await runFrozenBenchmark(pack,'SMALL',provider);assert.equal(run.packHash,pack.hash);assert.equal(run.results.length,SMALL_PROFILE.length);assert.ok(verifyFrozenBenchmarkPack(pack));});
test('structured provider adapter validates frozen task output without provider-specific domain coupling',async()=>{const document=documentOf(['청년 특별공급 신청자 본인 월평균소득 140% 이하']),pack=buildFrozenBenchmarkPack(document,extractFacts(document)),provider=createStructuredBenchmarkProvider('gemini-rest','offline',{async generate(){return {bindings:[],unresolved:[]};}});const task=pack.tasks.find(item=>item.taskId==='youth.income')!;assert.deepEqual(await provider.bind(task),{bindings:[],unresolved:[]});});
test('comparison classification prioritizes safety blockers over recall',()=>{const metric=(n:number,d:number):AuditMetric=>({numerator:n,denominator:d,measured:true,coverage:{evaluated:d,universe:d,ratio:1},methodology:'fixture',value:d?n/d:null});const run:any={packHash:'a'.repeat(64),provider:{id:'p',model:'m'},profile:'SMALL',results:Array.from({length:6},(_,index)=>({taskId:String(index),status:'SUCCESS',response:{bindings:[],unresolved:[]},error:null}))},perfect=metric(6,6);const row=compareModelResult({run,oraclePrecision:perfect,oracleRecall:perfect,numericFidelity:perfect,operatorFidelity:perfect,scoreFidelity:perfect,stageFidelity:perfect,semanticEvidenceSupport:perfect,scopeFidelity:perfect,exceptionRelationAccuracy:metric(1,1),hallucinationCount:1,highCriticalErrors:1,tokens:null,costUsd:null,safety:{criticalHallucination:1,wrongNumericBinding:0,wrongOperatorBinding:0,wrongScore:0,wrongScope:0,silentExceptionLoss:0,highConfidenceCriticalError:1}});assert.equal(row.classification,'SEMANTIC_UNSAFE');});
test('unavailable provider samples remain explicitly not measured',()=>{const metric=notMeasuredMetric(75,'provider returned no semantic sample');assert.equal(metric.measured,false);assert.equal(metric.numerator,null);assert.equal(metric.denominator,null);assert.deepEqual(metric.coverage,{evaluated:0,universe:75,ratio:0});const run:any={packHash:'a'.repeat(64),provider:{id:'p',model:'m'},profile:'SMALL',results:Array.from({length:6},(_,index)=>({taskId:String(index),status:'FAILED',response:null,error:'HTTP_429'}))};const row=compareModelResult({run,oraclePrecision:metric,oracleRecall:metric,numericFidelity:metric,operatorFidelity:metric,scoreFidelity:metric,stageFidelity:metric,semanticEvidenceSupport:metric,scopeFidelity:metric,exceptionRelationAccuracy:notMeasuredMetric(0,'not in profile'),hallucinationCount:0,highCriticalErrors:0,tokens:0,costUsd:0,safety:{criticalHallucination:0,wrongNumericBinding:0,wrongOperatorBinding:0,wrongScore:0,wrongScope:0,silentExceptionLoss:0,highConfidenceCriticalError:0}});assert.equal(row.classification,'INSUFFICIENT_SAMPLE');});

const root='.ingestion/announcements/990b2823e0ddc98fe7222815b6c844131bda6e9c1deac50c6de253eb0dbe524f',documentPath=`${root}/parsed/bd67d7ee6c9b9dbbe043f9c966679c791185ba0f21ae80050a33a489112e8763/document-parser-v1/document.json`,artifactDir=`${root}/extraction/samdo-ai-v4-plan-a16`;
test('v4 replay downgrades or rejects every original HIGH critical error',{skip:![documentPath,`${artifactDir}/samdo-v4-bindings.json`,`${artifactDir}/samdo-v4-rules.json`,`${artifactDir}/samdo-v4-oracle-comparison.json`].every(existsSync)},async()=>{const [documentRaw,bindingsRaw,rulesRaw,comparisonRaw]=await Promise.all([readFile(documentPath,'utf8'),readFile(`${artifactDir}/samdo-v4-bindings.json`,'utf8'),readFile(`${artifactDir}/samdo-v4-rules.json`,'utf8'),readFile(`${artifactDir}/samdo-v4-oracle-comparison.json`,'utf8')]);const document=JSON.parse(documentRaw) as ParsedDocument,bindings=JSON.parse(bindingsRaw),rules=JSON.parse(rulesRaw),comparison=JSON.parse(comparisonRaw),replay=replayV41(document,extractFacts(document),bindings.responses,rules.rules as CandidateRule[],comparison.highConfidenceCriticalErrors);assert.equal(replay.existingRules,74);assert.equal(replay.highCriticalErrorsBefore,14);assert.equal(replay.highCriticalErrorsRemaining,0,JSON.stringify(replay.rules.filter(row=>comparison.highConfidenceCriticalErrors.includes(row.candidateRuleId))));assert.equal(replay.highCriticalErrorsHandled,14);assert.equal(replay.ready,true);});
