export type Measurement='CORRECT'|'INCORRECT'|'NOT_MEASURED';
export type ExtraDisposition='SOURCE_SUPPORTED'|'UNVERIFIED_EXTRA'|'HALLUCINATION'|'NEEDS_HUMAN_REVIEW';
export type CandidateMetricReview={candidateRuleId:string;oracleMatched:boolean|null;extraDisposition?:ExtraDisposition;locatorValidity:Measurement;semanticEvidenceSupport:Measurement;oraclePreferredEvidenceMatch:Measurement;numericFidelity:Measurement;operatorFidelity:Measurement;scoreFidelity:Measurement;stageFidelity:Measurement;critical:boolean;highConfidenceCriticalError:boolean};
export type ConflictMetricReview={id:string;detected:boolean|null};
export type V3MetricArtifacts={oracleTargetCount:number|null;oracleComparisonPerformed:boolean;candidates:CandidateMetricReview[];unresolvedCount:number;conflicts:ConflictMetricReview[];knownConflictCount:number|null;silentExceptionDrops:number|null;coreCoverage:{YOUTH:boolean|null;NEWLYWED:boolean|null;FIRST_TIME:boolean|null};oracleNumericTargetCount?:number|null;oracleOperatorTargetCount?:number|null;oracleScoreTargetCount?:number|null;oracleStageTargetCount?:number|null};
export type MetricCounts={correct:number;evaluated:number;universe:number|null};
export type V3MetricInput={oracleTargets:number|null;oracleComparisonPerformed:boolean;matchedTargets:number;candidateTargets:number;matchedCandidateTargets:number;extras:Record<ExtraDisposition,number>;unresolved:number;conflicts:MetricCounts;locator:MetricCounts;semanticEvidence:MetricCounts;preferredEvidence:MetricCounts;criticalNumeric:MetricCounts;criticalOperators:MetricCounts;scores:MetricCounts;stages:MetricCounts;criticalHallucinations:number;highConfidenceCriticalErrors:number;silentExceptionDrops:number|null;coreCoverage:{YOUTH:boolean|null;NEWLYWED:boolean|null;FIRST_TIME:boolean|null}};
export type MetricAudit={numerator:number|null;denominator:number|null;measured:boolean;value:number|null;coverage:{evaluated:number;universe:number|null;ratio:number|null};methodology:string};

const count=(rows:CandidateMetricReview[],field:keyof CandidateMetricReview,universe:number|null=null):MetricCounts=>{const measured=rows.filter(row=>row[field]==='CORRECT'||row[field]==='INCORRECT');return {correct:measured.filter(row=>row[field]==='CORRECT').length,evaluated:measured.length,universe};};
export function buildV3MetricInput(artifacts:V3MetricArtifacts):V3MetricInput{
  const extras:Record<ExtraDisposition,number>={SOURCE_SUPPORTED:0,UNVERIFIED_EXTRA:0,HALLUCINATION:0,NEEDS_HUMAN_REVIEW:0};let matchedTargets=0,matchedCandidateTargets=0;
  for(const row of artifacts.candidates){if(row.oracleMatched===true){matchedTargets++;matchedCandidateTargets++;}else if(row.oracleMatched===false)extras[row.extraDisposition??'NEEDS_HUMAN_REVIEW']++;}
  const conflictMeasured=artifacts.conflicts.filter(row=>row.detected!==null);
  return {oracleTargets:artifacts.oracleTargetCount,oracleComparisonPerformed:artifacts.oracleComparisonPerformed,matchedTargets,candidateTargets:artifacts.candidates.length,matchedCandidateTargets,extras,unresolved:artifacts.unresolvedCount,conflicts:{correct:conflictMeasured.filter(row=>row.detected).length,evaluated:conflictMeasured.length,universe:artifacts.knownConflictCount},locator:count(artifacts.candidates,'locatorValidity',artifacts.candidates.length),semanticEvidence:count(artifacts.candidates,'semanticEvidenceSupport',artifacts.candidates.length),preferredEvidence:count(artifacts.candidates,'oraclePreferredEvidenceMatch',artifacts.oracleTargetCount),criticalNumeric:count(artifacts.candidates,'numericFidelity',artifacts.oracleNumericTargetCount??null),criticalOperators:count(artifacts.candidates,'operatorFidelity',artifacts.oracleOperatorTargetCount??null),scores:count(artifacts.candidates,'scoreFidelity',artifacts.oracleScoreTargetCount??null),stages:count(artifacts.candidates,'stageFidelity',artifacts.oracleStageTargetCount??null),criticalHallucinations:artifacts.candidates.filter(row=>row.critical&&row.oracleMatched===false&&row.extraDisposition==='HALLUCINATION').length,highConfidenceCriticalErrors:artifacts.candidates.filter(row=>row.highConfidenceCriticalError).length,silentExceptionDrops:artifacts.silentExceptionDrops,coreCoverage:artifacts.coreCoverage};
}
const audit=(counts:MetricCounts,methodology:string):MetricAudit=>({numerator:counts.evaluated?counts.correct:null,denominator:counts.evaluated?counts.evaluated:null,measured:counts.evaluated>0,value:counts.evaluated?counts.correct/counts.evaluated:null,coverage:{evaluated:counts.evaluated,universe:counts.universe,ratio:counts.universe===null?null:counts.evaluated/Math.max(counts.universe,1)},methodology});
const comparisonAudit=(correct:number,denominator:number|null,measured:boolean,methodology:string,coverageUniverse:number|null):MetricAudit=>({numerator:measured?correct:null,denominator:measured?denominator:null,measured,value:measured&&denominator?correct/denominator:null,coverage:{evaluated:measured?(denominator??0):0,universe:coverageUniverse,ratio:measured&&coverageUniverse!==null?(denominator??0)/Math.max(coverageUniverse,1):null},methodology});
export function calculateV3Metrics(input:V3MetricInput){const precisionMeasured=input.oracleComparisonPerformed&&input.candidateTargets>0,recallMeasured=input.oracleComparisonPerformed&&input.oracleTargets!==null;return {oracleTargetPrecision:comparisonAudit(input.matchedCandidateTargets,input.candidateTargets,precisionMeasured,'Oracle alignment reviewed per generated candidate.',input.candidateTargets),oracleTargetRecall:comparisonAudit(input.matchedTargets,input.oracleTargets,recallMeasured,'Oracle targets matched after provider execution; missing targets stay in the denominator.',input.oracleTargets),extras:{...input.extras,methodology:'Unmatched candidates default to NEEDS_HUMAN_REVIEW until source review classifies them.'},unresolved:input.unresolved,conflictDetection:audit(input.conflicts,'Known conflicts with an explicit detected true/false review.'),evidence:{locatorValidity:audit(input.locator,'Locator validated against ParsedDocument IDs.'),semanticSupport:audit(input.semanticEvidence,'Evidence reviewed for semantic support of the role.'),oraclePreferredMatch:audit(input.preferredEvidence,'Evidence compared with the oracle preferred locator.')},fidelity:{numeric:audit(input.criticalNumeric,'Mapped numeric values compared with oracle atoms.'),operator:audit(input.criticalOperators,'Mapped operators compared with oracle atoms.'),score:audit(input.scores,'Mapped score values compared with oracle atoms.'),stage:audit(input.stages,'Mapped stages compared with oracle atoms.')}};}
export function adminReviewReady(input:V3MetricInput){const m=calculateV3Metrics(input);const blockers:string[]=[];if(!m.fidelity.numeric.measured||m.fidelity.numeric.value!==1)blockers.push('CRITICAL_NUMERIC_FIDELITY');if(!m.fidelity.operator.measured||m.fidelity.operator.value!==1)blockers.push('CRITICAL_OPERATOR_FIDELITY');if(!m.fidelity.score.measured||m.fidelity.score.value!==1)blockers.push('SCORE_FIDELITY');if(!m.fidelity.stage.measured||m.fidelity.stage.value!==1)blockers.push('STAGE_FIDELITY');if(input.criticalHallucinations)blockers.push('CRITICAL_HALLUCINATION');if(input.highConfidenceCriticalErrors)blockers.push('HIGH_CONFIDENCE_CRITICAL_ERROR');if(input.silentExceptionDrops===null)blockers.push('EXCEPTION_PRESERVATION_NOT_MEASURED');else if(input.silentExceptionDrops)blockers.push('SILENT_EXCEPTION_DROP');if(!m.evidence.locatorValidity.measured||(m.evidence.locatorValidity.value??0)<.99)blockers.push('EVIDENCE_LOCATOR_VALIDITY');for(const [scope,covered] of Object.entries(input.coreCoverage))if(covered!==true)blockers.push(`CORE_COVERAGE_${scope}`);return {ready:blockers.length===0,blockers,metrics:m};}
