import type { ParsedDocument } from '../parsedDocument.ts';
import type { ExtractedFact } from './facts.ts';
import { GEMINI_SAFE_BINDING_SCHEMA } from './contract.ts';
import { buildTaskInput,V3_TASKS,type SemanticTaskInput } from './tasks.ts';

export const PLAN_A_16=['common.regionPriority','youth.coreEligibility','youth.income','youth.assets','youth.stages','youth.score','youth.exceptions','newlywed.coreEligibility','newlywed.financial','newlywed.stages','newlywed.score','newlywed.exceptions','firstTime.coreEligibility','firstTime.financial','firstTime.stages','firstTime.exceptions'] as const;
export const PLAN_B_24=[...PLAN_A_16,'youth.basicEligibility','youth.subscription','newlywed.applicantEligibility','newlywed.subscription','newlywed.homelessDuration','firstTime.subscriptionSavings','firstTime.taxHistory','firstTime.income'] as const;
export type PlanRow={taskName:string;scope:string;stage:string;inputChars:number;tableCount:number;blockCount:number;factCount:number;factsAvailable:number;factsAfterTypeFilter:number;factsAfterContextFilter:number;factsSelected:number;sourcesAvailable:number;sourcesSelected:number;droppedFactCount:number;truncated:boolean;expectedBindings:{min:number;max:number};estimatedOutputSchemaSize:number;status:'READY'|'NO_CONTEXT'|'NOT_READY_MISSING_FACT'|'NOT_READY_MISSING_OPERATOR'};
export function buildCallPlan(document:ParsedDocument,facts:ExtractedFact[],plan:'PLAN_A_16'|'PLAN_B_24'):{name:string;rows:PlanRow[];inputs:SemanticTaskInput[]} {
  const names=plan==='PLAN_A_16'?PLAN_A_16:PLAN_B_24,schemaBytes=JSON.stringify(GEMINI_SAFE_BINDING_SCHEMA).length;
  const inputs=names.map(name=>{const definition=V3_TASKS.find(task=>task.name===name);if(!definition)throw new Error(`UNKNOWN_TASK:${name}`);const input=buildTaskInput(document,facts,definition);input.schemaBytes=schemaBytes;return input;});
  return {name:plan,inputs,rows:inputs.map(input=>{const coverage=Object.values(input.selection.roleCoverage),status=!input.sources.length?'NO_CONTEXT':coverage.some(item=>item.status==='NOT_READY_MISSING_OPERATOR')?'NOT_READY_MISSING_OPERATOR':coverage.some(item=>item.status==='NOT_READY_MISSING_FACT')?'NOT_READY_MISSING_FACT':'READY';return {taskName:input.task.name,scope:input.task.scope,stage:input.task.stage,inputChars:input.inputChars,tableCount:input.tableCount,blockCount:input.blockCount,factCount:input.facts.length,factsAvailable:input.selection.factsAvailable,factsAfterTypeFilter:input.selection.factsAfterTypeFilter,factsAfterContextFilter:input.selection.factsAfterContextFilter,factsSelected:input.selection.factsSelected,sourcesAvailable:input.selection.sourcesAvailable,sourcesSelected:input.selection.sourcesSelected,droppedFactCount:input.selection.droppedFactCount,truncated:input.selection.truncated,expectedBindings:input.task.expectedBindings,estimatedOutputSchemaSize:schemaBytes,status};})};
}
