import test from 'node:test';
import assert from 'node:assert/strict';
import { existsSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import type { ParsedBlock,ParsedDocument,SourceLocator } from '../parsedDocument.ts';
import { extractFacts } from '../v3/facts.ts';
import { buildTaskInput,V3_TASKS } from '../v3/tasks.ts';
import { PLAN_A_16,PLAN_B_24,buildCallPlan } from '../v3/plans.ts';
import { discoverExceptionSources } from '../v3/exceptions.ts';
import { buildCandidateRules,deriveHostConfidence,deriveReviewDisposition } from '../v3/ruleBuilder.ts';
import { buildOfflineRetrievalScorecard } from './scorecard.ts';

const locator=(paragraphIndex:number):SourceLocator=>({kind:'HWP_RECORD',pageNumber:null,stream:'BodyText/Section0',recordOffset:paragraphIndex*10,recordLevel:0,paragraphIndex});
function documentOf(texts:string[]):ParsedDocument{const blocks:ParsedBlock[]=texts.map((text,index)=>({id:`b${String(index).padStart(6,'0')}`,type:'paragraph',text,sectionPath:[],sourceLocator:locator(index)})),text=blocks.map(block=>block.text).join('\n');return {schemaVersion:1,documentId:`sha256:${'c'.repeat(64)}`,sha256:'c'.repeat(64),mimeType:'application/x-hwp',parserVersion:'document-parser-v1',status:'PARSED',pages:null,blocks,tables:[],metadata:{},quality:{textBlockCount:blocks.length,tableCount:0,characterCount:[...text].length,emptyBlockRatio:0,replacementCharacterCount:0,suspiciousEncoding:false,parserWarnings:[],extractionAllowed:true}};}
const task=(name:string)=>V3_TASKS.find(item=>item.name===name)!;

test('role retrieval excludes childbirth percentages from youth income',()=>{const document=documentOf(['청년 특별공급 신청자 본인 월평균소득 140% 이하','청년 출산가구 소득기준 완화 1명 10%p, 2명 20%p']);const input=buildTaskInput(document,extractFacts(document),task('youth.income'));assert.ok(input.facts.some(fact=>fact.normalizedValue===140));assert.ok(input.facts.every(fact=>fact.normalizedValue!==10&&fact.normalizedValue!==20));});
test('asset retrieval excludes subscription savings',()=>{const document=documentOf(['생애최초 특별공급 세대 총자산 362백만원 이하','생애최초 특별공급 청약저축 선납금 포함 600만원 이상']);const input=buildTaskInput(document,extractFacts(document),task('firstTime.financial'));assert.ok(input.facts.some(fact=>fact.normalizedValue===362_000_000));assert.ok(input.facts.every(fact=>fact.normalizedValue!==6_000_000));});
test('range facts preserve both bounds and operators',()=>{const document=documentOf(['청년 특별공급 가점 70% 초과 100% 이하, 12회 이상 24회 미만']);const ranges=extractFacts(document).filter(fact=>fact.type==='RANGE');assert.deepEqual(ranges.map(fact=>fact.range),[{lowerValue:70,lowerOperator:'gt',upperValue:100,upperOperator:'lte',unit:'PERCENT'},{lowerValue:12,lowerOperator:'gte',upperValue:24,upperOperator:'lt',unit:'PAYMENT_COUNT'}]);});
test('numeric rule without operator is unresolved instead of equality fallback',()=>{const document=documentOf(['청년 특별공급 신청자 본인 월평균소득 140%']),facts=extractFacts(document),fact=facts.find(item=>item.type==='PERCENT')!;const binding={bindingId:'x',semanticRole:'YOUTH.INCOME_LIMIT',factIds:[fact.factId],sourceIds:[fact.sourceId],qualifierSourceIds:[]};assert.deepEqual(buildCandidateRules(document,task('youth.income'),binding,facts).unresolved,['MISSING_OPERATOR:x']);});
test('contextual exception marker alone is noise but combined context is reviewable',()=>{const document=documentOf(['배우자가 신청합니다.','배우자 혼인 전 주택소유 후 처분 예외']);const found=discoverExceptionSources(document);assert.deepEqual(found.map(item=>item.sourceId),['b000001']);const facts=extractFacts(document),fact=facts.find(item=>item.sourceId==='b000001')!,binding={bindingId:'e',semanticRole:'FIRST_TIME.EXCEPTION',factIds:[fact.factId],sourceIds:[fact.sourceId],qualifierSourceIds:[]};assert.equal(deriveHostConfidence(document,binding,[fact]).level,'REVIEW_REQUIRED');});
test('host review disposition prioritizes safe candidates without implying approval',()=>{assert.equal(deriveReviewDisposition({level:'HIGH',reason:'single deterministic source'}),'AUTO_SAFE_CANDIDATE');assert.equal(deriveReviewDisposition({level:'MEDIUM',reason:'multiple sources'}),'REVIEW_REQUIRED');assert.equal(deriveReviewDisposition({level:'HIGH',reason:'source'},1),'UNRESOLVED');});
test('fact layer preserves applicant, household and parent scope metadata',()=>{const document=documentOf(['청년 특별공급 신청자 본인 자산 276백만원 이하, 부모 자산 1,034백만원 이하','신혼부부 특별공급 세대 총자산 362백만원 이하']);const facts=extractFacts(document);assert.ok(facts.some(fact=>fact.normalizedValue===276_000_000&&fact.applicantScopes.includes('APPLICANT')));assert.ok(facts.some(fact=>fact.normalizedValue===1_034_000_000&&fact.applicantScopes.includes('PARENT')));assert.ok(facts.some(fact=>fact.normalizedValue===362_000_000&&fact.applicantScopes.includes('HOUSEHOLD')));});
test('plans preserve exception tasks and PLAN_B is a superset',()=>{for(const name of PLAN_A_16)assert.ok(PLAN_B_24.includes(name));for(const name of ['youth.exceptions','newlywed.exceptions','firstTime.exceptions'])assert.ok(PLAN_A_16.includes(name as never));});
test('selection telemetry exposes filtering and truncation counts',()=>{const document=documentOf(['청년 특별공급 신청자 본인 월평균소득 140% 이하','청년 특별공급 신청자 본인 월평균소득 100% 이하']);const row=buildCallPlan(document,extractFacts(document),'PLAN_A_16').rows.find(item=>item.taskName==='youth.income')!;assert.ok(row.factsAvailable>=row.factsAfterContextFilter);assert.equal(row.factsSelected,row.factCount);assert.ok(row.sourcesAvailable>=row.sourcesSelected);});

const samdoPath='.ingestion/announcements/990b2823e0ddc98fe7222815b6c844131bda6e9c1deac50c6de253eb0dbe524f/parsed/bd67d7ee6c9b9dbbe043f9c966679c791185ba0f21ae80050a33a489112e8763/document-parser-v1/document.json';
test('Samdo offline retrieval gate covers every critical fact without known wrong facts',{skip:!existsSync(samdoPath)},async()=>{const document=JSON.parse(await readFile(samdoPath,'utf8')) as ParsedDocument,scorecard=buildOfflineRetrievalScorecard(document,extractFacts(document));assert.equal(scorecard.wrongFactCount,0);assert.equal(scorecard.missingOperatorFallback,0);assert.equal(scorecard.scoreTableCoverage,true);assert.equal(scorecard.planBSuperset,true);assert.equal(scorecard.exceptionTasks,true);assert.ok(scorecard.rows.every(row=>row.coverage===1),JSON.stringify(scorecard.rows.filter(row=>row.coverage!==1)));assert.equal(scorecard.ready,true);});
